# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecdf_cpp <- function(reference, sample) {
    .Call('_cfdr_ecdf_cpp', PACKAGE = 'cfdr', reference, sample)
}

approx_cpp <- function(x, y, xout) {
    .Call('_cfdr_approx_cpp', PACKAGE = 'cfdr', x, y, xout)
}

vl_mode2 <- function(p, q, indices, fold, adj = TRUE, at = NULL, nt = 5000L, nv = 1000L, p_threshold = 0, scale = as.character( c("p", "z")), closed = TRUE, verbose = FALSE, gx = 0.00001) {
    .Call('_cfdr_vl_mode2', PACKAGE = 'cfdr', p, q, indices, fold, adj, at, nt, nv, p_threshold, scale, closed, verbose, gx)
}

