# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Empirical cdf
#'
#' @description This function estimates an empirical cdf using the reference parameter and then 
#' evaluates the estimated empirical cdf at the points specified in the sample parameter. 
#' 
#' @param reference NumericVector containing reference points to which to fit empirical cdf
#' @param sample NumericVector containing points at which to evaluate empirical cdf
#' @return NumericVector of estimated quantiles of sample values
#' 
#' @author Tom Willis
ecdf_cpp <- function(reference, sample) {
    .Call(`_cfdr_ecdf_cpp`, reference, sample)
}

#' @title Linear interpolation function
#'
#' @description This function carries out linear interpolation, reproducing a subset of the behaviour of stats::approx in R.
#'
#' @details Linear interpolation is performed with f(x)=f(x0)+[(f(x1)-f(x0))/(x1-x0)]*(x-x0). x is assumed to be sorted; if sorted in descending order, the order of elements in x and y is reversed. If a value of xout lies outside the range [min(x), max(x)], the value is interpolated using the nearest extremum (this corresponds to the behaviour of stats::approx with method=2).
#'
#' @param x NumericVector of x coordinates of points to be interpolated
#' @param y NumericVector of y coordinates of points to be interpolated
#' @param xout NumericVector of points at which to interpolate
#'
#' @return NumericVector of interpolated values 
#' 
#' @author Tom Willis
approx_cpp <- function(x, y, xout) {
    .Call(`_cfdr_approx_cpp`, x, y, xout)
}

#' @title Returns coordinates of L-regions for cFDR method.
#'
#' @description Drop-in replacement for the cfdr::vl function in the use case wherein indices and fold are supplied and mode=2.
#' 
#' @param p principal p-values
#' @param q conditional p-values
#' @param adj adjust cFDR values and hence curves L using estimate of Pr(H0|Pj<pj)
#' @param indices indices of points at which to compute v(L)
#' @param at cfdr cutoff/cutoffs. Defaults to null
#' @param fold indices of points to exclude when from calculation of L-curves 
#' @param p_threshold if H0 is to be rejected automatically whenever p<p_threshold, include this in all regions L
#' @param nt number of test points in x-direction, default 5000
#' @param nv resolution for constructing L-curves, default 1000
#' @param scale return curves on the p- or z- plane. Y values are equally spaced on the z-plane.
#' @param closed determines whether curves are closed polygons encircling regions L (closed=T), or lines indicating the rightmost border of regions L
#' @return list containing elements x, y. Assuming n curves are calculated (where n=length(indices) or length(at)) and closed=T, x is a matrix of dimension n x (4+nv), y ix a vector of length (4+nv).
#' 
#' @author Tom Willis
vl_mode2 <- function(p, q, indices, fold, adj = TRUE, at = NULL, nt = 5000L, nv = 1000L, p_threshold = 0, scale = as.character( c("p", "z")), closed = TRUE, gx = 0.00001) {
    .Call(`_cfdr_vl_mode2`, p, q, indices, fold, adj, at, nt, nv, p_threshold, scale, closed, gx)
}

